### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by trappedinspacetime** [pxntus/txt2pdf#1]
First of all thank you for making this tool. I am on Ubuntu 16.04 platform. I cloned and run the command in the description. However, I get the following error message:

          python txt2pdf.py --help
          File "txt2pdf.py", line 69
          print("Warning: Unfinished emphasized text marker!", file=sys.stderr)
                                                             ^
          SyntaxError: invalid syntax

**Comment by pxntus** [comment]
You need to use Python 3, i.e.:

`python3 txt2pdf.py --help`

When you tried this the instruction wasn't up to date and the script didn't really work on Linux. That is hopefully fixed now.
